Set the normative definition of Multikey to the Data Integrity spec.
w3c/vc-di-ecdsa pull request #16
Opened 2023-07-09 20:34 UTC by msporny

This PR points the ECDSA Cryptosuites to the normative definition of Multikey in the VC Data Integrity specification (instead of re-defining it in the ECDSA cryptosuite specification). This allows much of the normative language to now be deduplicated between the VC Data Integrity spec and the ECDSA cryptosuite.

2023-07-09 21:11 UTC, dlongley requested changes

2023-07-09 21:11 UTC, dlongley commented on index.html
> +the two-byte prefix `0x1200` followed by the 33-byte compressed public key data.
```suggestion
the two-byte prefix `0x8024` (the varint expression of `0x1200`) followed
by the 33-byte compressed public key data.
```

2023-07-09 21:11 UTC, dlongley commented on index.html
> +base58-btc (`z`) as the prefix. Any other encodings MUST NOT be allowed.
```suggestion
The 35 byte value is then encoded using base58-btc (`z`) as the prefix. The
encoding of a P-384 public key is the two-byte prefix `0x8124` (the varint
expression of `0x1201`) followed by the 49-byte compressed public key data.
The 51 byte value is then encoded using base58-btc (`z`) as the prefix. Any
other encodings MUST NOT be allowed.
```

2023-07-10 15:33 UTC, Wind4Greg approved these changes
Nice to have the details of the representation right in the specification.

2023-07-10 18:23 UTC, TallTed commented on index.html
> +processes that result in equivalent cryptographic key material MAY be utilized
```suggestion
processes that result in equivalent cryptographic key material MAY be used
```

2023-07-10 18:24 UTC, TallTed commented on index.html
> +The 51 byte value is then encoded using base58-btc (`z`) as the prefix. Any
```suggestion
The 35-byte value is then encoded using base58-btc (`z`) as the prefix. The
encoding of a P-384 public key is the two-byte prefix `0x8124` (the varint
expression of `0x1201`) followed by the 49-byte compressed public key data.
The 51-byte value is then encoded using base58-btc (`z`) as the prefix. Any
```

2023-07-10 20:13 UTC, dlongley approved these changes

2023-07-14 13:05 UTC, martyr280 approved these changes

2023-07-23 22:55 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-07-23 22:55 UTC, merged