Add Greg and Sebastian as Editors to ECDSA Cryptosuites
w3c/vc-di-ecdsa pull request #17
Opened 2023-07-09 21:10 UTC by msporny

This PR adds Greg and Sebastian as Editors to the ECDSA Cryptosuites. The PR shouldn't be processed until after Sebastian's IE application has been processed. /cc @Wind4Greg @seabass-labrax

2023-07-09 21:15 UTC, dlongley approved these changes

2023-07-10 06:17 UTC, iherman commented
See my comment in https://github.com/w3c/vc-di-eddsa/pull/50#issuecomment-1628305781

2023-07-11 10:08 UTC, seabass-labrax requested changes

2023-07-11 10:08 UTC, seabass-labrax commented on index.html
> +          company: "Invited Expert", w3cid: 0
```suggestion
          company: "Invited Expert", w3cid: 140132
```

2023-07-11 20:48 UTC, brentzundel approved these changes

2023-07-13 21:54 UTC, msporny commented on index.html
> +          company: "Invited Expert", w3cid: 0
```suggestion
          company: "Invited Expert", w3cid: 140479
```

2023-07-14 13:04 UTC, martyr280 approved these changes

2023-07-23 22:53 UTC, msporny commented
@seabass-labrax is now a member of the VCWG, merging.

2023-07-23 22:54 UTC, merged