Update selective disclosure functions and their use in ecdsa-sd sign, derive, verify.
w3c/vc-di-ecdsa pull request #27
Opened 2023-08-15 06:24 UTC by dlongley

This PR updates the underlying selective disclosure functions to remove the need to use the JSON-LD framing primitive and to remove the special treatment of `credentialSubject` for VCs. It accomplishes this by using JSON pointers for selection (filtering and grouping) and skolemization of expanded (and subsequently compacted) JSON-LD documents instead of direct skolemization of N-Quads. Grouping and filter functions have been removed and replaced with a single `canonicalizeAndGroup` function, and the previous `jsonPointersToFrame` function has been adjusted to `selectJsonLd` as it now performs selection directly on skolemized, compact JSON-LD documents instead of producing a frame as an intermediate step.

The formats / expression of proof data in ecdsa-sd is unchanged, only the internals used to implement it are updated.

A few other corrections were made around label factory function production.

Some editorial clean up still needs to be done around the use of `<var>`, `<em>` and quoting variables using backticks, but this is not a new issue.

2023-08-15 16:04 UTC, Wind4Greg approved these changes
This is a nice improvement to the internal selective disclosure processing (both mandatory reveal, and selective reveal) to remove the dependency on JSON-LD framing. Key functionality is encapsulated in the `canonicalizeAndGroup` function.

It should be noted that besides the ECDSA algorithms from FIPS-186-5 (2023) that the EdDSA algorithms (Ed25519, Ed448) can be used. In addition the SD primitives particularly `canonicalizeAndGroup` maybe applicable for applying BBS to VCs.

2023-08-15 21:08 UTC, TallTed requested changes

2023-08-15 21:08 UTC, TallTed commented on index.html
> +produced as output.
```suggestion
The required inputs are a compact JSON-LD document (<var>document</var>),
a label map factory function (<var>labelMapFactoryFunction</var>), and a map
of named group definitions (<var>groupDefinitions</var>). Additional custom
options (such as a document loader) can be passed. The <var>document</var> is
assumed to use a JSON-LD context that aliases `@id` and `@type` to `id` and
`type`, respectively, and to use only one <em>`@context`</em> property at the top
level of the document. An object containing the created groups
(<var>groups</var>), the skolemized compact JSON-LD document
(<var>skolemizedCompactDocument</var>), the skolemized expanded JSON-LD
document (<var>skolemizedExpandedDocument</var>), the deskolemized N-Quad
strings (<var>deskolemizedNQuads</var>), the blank node label map
(<var>labelMap</var>), and the canonical N-Quad strings <var>nquads</var>, is
produced as output.
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +passing <var>document</var> and any custom options.
```suggestion
passing <var>document</var> with any custom options.
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +<var>skolemizedExpandedDocument</var> and any custom options.
```suggestion
<var>skolemizedExpandedDocument</var> with any custom options.
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +<var>labelMapFactoryFunction</var>, and any custom options.
```suggestion
and <var>labelMapFactoryFunction</var>, with any custom options.
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +<var>skolemizedCompactDocument</var> as <var>document</var>,
```suggestion
<var>skolemizedCompactDocument</var> as <var>document</var>, with
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +to <var>matching</var>, otherwise add <var>entry</var> to <var>nonMatching</var>.
```suggestion
to <var>matching</var>; otherwise, add <var>entry</var> to <var>nonMatching</var>.
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +Initialize `labelMapFactoryFunction` to the result of callign the
```suggestion
Initialize `labelMapFactoryFunction` to the result of calling the
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +and value of `combinedPointers`.
```suggestion
Initialize `groupDefinitions` to a map with the following entries: key of
the string `"mandatory"` and value of `mandatoryPointers`, key of the string
`"selective"` and value of `selectivePointers`, and key of the string `"combined"`
and value of `combinedPointers`.
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +based on `hmac` and groups the N-Quad strings according to selections based on
```suggestion
based on `hmac`, and groups the N-Quad strings according to selections based on
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +canonicalize the reveal document to the blank node identifiers that were
```suggestion
canonicalize the revealed document to the blank node identifiers that were
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +Initialize `labelMapFactoryFunction` to the result of callign the
```suggestion
Initialize `labelMapFactoryFunction` to the result of calling the
```

2023-08-15 21:08 UTC, TallTed commented on index.html
> +N-Quads with pseudorandom blank node identifiers based on `hmac` and groups
```suggestion
N-Quads with pseudorandom blank node identifiers based on `hmac`, and groups
```

2023-08-15 21:26 UTC, dlongley commented
@TallTed,

Thanks heaps! So I applied all of your suggestions except for the ones that changed the use of "and" when talking about passing parameters. Those suggest using "with" instead and I'm not sure that "with" is better?

Without that suggestion we have examples like this:

> Use algorithm X, passing foo as A and B.
> Use algorithm X, passing foo as A, bar as B, and C.

With that suggestion it would read like this:

> Use algorithm X, passing foo as A with B.
> Use algorithm X, passing foo as A, bar as B, with C.

I'm not sure what the consensus is, but "and" reads better to me. I can how the use of "with" reads alright when C is for example "any custom options":

> Use algorithm X, passing foo as A, bar as B, and any custom options.
vs.
> Use algorithm X, passing foo as A, bar as B, with any custom options.

But "and" still reads better to me personally and is consistent. Thoughts?

2023-08-15 22:15 UTC, TallTed commented
Maybe...

Use algorithm X, passing A, and foo as B.
Use algorithm X, passing A, foo as B, and bar as C.
Use algorithm X, passing A, foo as B, and bar as C, along with any custom options.

2023-08-15 23:25 UTC, dlongley commented
@TallTed,

> Maybe...
> 
> Use algorithm X, passing A, and foo as B.
> Use algorithm X, passing A, foo as B, and bar as C.
> Use algorithm X, passing A, foo as B, and bar as C, along with any custom options.

I'd be fine with that, but I'm also fine to just leave it as always using "and". If you want to adjust your suggestions accordingly, I'll add them in.

2023-08-16 03:40 UTC, TallTed requested changes
Revised the `passing ... and` vs `passing ... with`

2023-08-16 03:40 UTC, TallTed commented on index.html
> +<var>pointers</var>.
```suggestion
in Section <a href="#selectjsonld"></a>, passing <var>pointers</var>,
and <var>skolemizedCompactDocument</var> as <em>document</em>.
```

2023-08-16 03:40 UTC, TallTed commented on index.html
> +<var>selectionDocument</var> as <var>skolemizedCompactDocument</var>, with
```suggestion
<var>selectionDocument</var> as <var>skolemizedCompactDocument</var>, and
```

2023-08-16 03:40 UTC, TallTed commented on index.html
> +<var>labelMapFactoryFunction</var>, and any custom options.
```suggestion
<var>labelMapFactoryFunction</var>, <var>deskolemizedNQuads</var> as
<var>nquads</var>, and any custom options.
```

2023-08-16 03:40 UTC, TallTed commented on index.html
> +<var>pointers</var>, <var>labelMap</var>, and any custom options.
```suggestion
<var>pointers</var>, <var>labelMap</var>, <var>skolemizedCompactDocument</var>
as <var>document</var>, and any custom options.
```

2023-08-16 03:40 UTC, TallTed commented on index.html
> +algorithm, passing `document`, with `combinedPointers` as `pointers`.
```suggestion
algorithm, passing `document`, and `combinedPointers` as `pointers`.
```

2023-08-16 03:40 UTC, TallTed commented on index.html
> +the N-Quad strings according to selections based on JSON pointers.
```suggestion
<a href="#canonicalizeandgroup"></a>, passing `labelMapFactoryFunction`,
`groupDefinitions`, `unsecuredDocument` as `document`, and any custom JSON-LD
API options. Note: This step transforms the document into an array of canonical
N-Quads with pseudorandom blank node identifiers based on `hmac`, and groups
the N-Quad strings according to selections based on JSON pointers.
```

2023-08-16 18:47 UTC, Wind4Greg commented
Hi Dave working on high level test vectors. Noticed redundant step to canonize proofOptions in section 3.5.3 Base Proof Hashing (ecdsa-sd-2023), this is already done in at the end of section 3.5.4 Base Proof Configuration (ecdsa-sd-2023)  -- step 9.

2023-08-16 18:52 UTC, dlongley commented
@Wind4Greg,

Since there's considerable reworking done in this PR and still some editorial clean up to be done later, I'd like us to get this merged and then work off it as a baseline. That should include any simplifications like you mentioned.

2023-08-17 18:54 UTC, msporny approved these changes

2023-08-17 19:02 UTC, TallTed approved these changes

2023-08-22 14:57 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-08-22 14:57 UTC, merged