Simplify language that warns of invalid examples
w3c/vc-di-ecdsa pull request #31
Opened 2023-08-18 14:03 UTC by seabass-labrax

This commit contains a minor improvement to a paragraph early in the specification. See also <https://github.com/w3c/vc-di-eddsa/pull/59>.

2023-08-18 15:04 UTC, dlongley approved these changes

2023-08-18 17:51 UTC, TallTed commented on index.html
> +explaining certain portions and ellipsis (`...`) indicating the omision of
```suggestion
explaining certain portions and ellipses (`...`) indicating the omission of
```

2023-08-18 18:53 UTC, seabass-labrax commented on index.html
> +explaining certain portions and ellipsis (`...`) indicating the omision of
Thanks; corrected and pushed.

2023-08-18 22:08 UTC, Wind4Greg approved these changes

2023-08-21 18:42 UTC, TallTed requested changes

2023-08-21 21:56 UTC, seabass-labrax commented
To be quite honest, we use this invalid JSON in neither vc-di-eddsa nor vc-di-ecdsa currently. Maybe we should just delete the paragraph entirely, and add something based on what we end up using closer to publication (if any invalid JSON at all).

2023-08-21 23:33 UTC, TallTed commented
> we use this invalid JSON in neither vc-di-eddsa nor vc-di-ecdsa currently

OH! Yes, we should only include the paragraph about invalid JSON in docs where we have such invalid JSON.

2023-08-28 12:15 UTC, martyr280 approved these changes

2023-09-02 21:18 UTC, msporny approved these changes

2023-09-02 21:19 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2023-09-02 21:19 UTC, merged