Make all Multicodec / Multibase references non-normative.
w3c/vc-di-ecdsa pull request #42
Opened 2023-09-27 13:51 UTC by msporny

This PR attempts to address issue #39 by making all Multicodec / Multibase references non-normative and cites the normative sections of PR https://github.com/w3c/vc-data-integrity/pull/196 as requested by the issue submitter.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-ecdsa/pull/42.html" title="Last updated on Oct 6, 2023, 8:47 PM UTC (668357b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-ecdsa/42/2095117...668357b.html" title="Last updated on Oct 6, 2023, 8:47 PM UTC (668357b)">Diff</a>

2023-09-27 16:00 UTC, dlongley approved these changes

2023-09-27 16:38 UTC, decentralgabe approved these changes

2023-09-27 16:51 UTC, selfissued requested changes
This PR doesn't do the job.  The point of the issue was to remove the references - not to make them non-normative.  Making them non-normative means that required fields are undefined, which is unacceptable for a standard.

Instead, remove the references to multibase and add normative text fully defining the contents of the fields.

2023-09-27 17:23 UTC, iherman requested changes
See my comment in https://github.com/w3c/vc-di-eddsa/pull/63; it is verbatim relevant for this PR, too

2023-09-27 19:00 UTC, TallTed requested changes
Small stuff

2023-09-27 19:00 UTC, TallTed commented on index.html
>  and the representation for the private key, <code>p384-priv</code>, are shown below.
```suggestion
[[?MULTIBASE]]/[[?MULTICODEC]] representation of the public key, <code>p384-pub</code>,
and the representation of the private key, <code>p384-priv</code>, are shown below.
```

2023-09-27 19:00 UTC, TallTed commented on index.html
>  and the representation for the private key, <code>p256-priv</code>, are shown below.
```suggestion
[[?MULTIBASE]]/[[?MULTICODEC]] representation of the public key, <code>p256-pub</code>,
and the representation of the private key, <code>p256-priv</code>, are shown below.
```

2023-09-27 19:00 UTC, TallTed commented on index.html
>  and the representation for the private key, <code>p384-priv</code>, are shown below.
```suggestion
[[?MULTIBASE]]/[[?MULTICODEC]] representation of the public key, <code>p384-pub</code>,
and the representation of the private key, <code>p384-priv</code>, are shown below.
```

2023-09-28 00:05 UTC, Wind4Greg approved these changes

2023-09-28 01:36 UTC, iherman commented
My original review comment is moot,  in view of https://github.com/w3c/vc-data-integrity/pull/196#issuecomment-1738316947. Changing the review.

2023-09-30 14:29 UTC, msporny commented
@selfissued there are now no references to the IETF I-Ds on Multiformats, we instead either normatively define the values needed in the spec, or refer back to VC Data Integrity, which defines the values needed. Requesting re-review.

2023-10-03 12:13 UTC, TallTed approved these changes

2023-10-04 16:40 UTC, selfissued requested changes
This spec is still referencing ?MULTIBASE rather than normative definitions of the features used.

Many of the comments in https://github.com/w3c/vc-di-eddsa/pull/63#pullrequestreview-1657950868 and https://github.com/w3c/vc-data-integrity/pull/196#pullrequestreview-1657894864 also apply to this specification.

In particular, the referenced terms need be normatively defined in sufficient detail to enable interoperable implementations.

2023-10-06 14:25 UTC, martyr280 approved these changes

2023-10-06 14:28 UTC, seabass-labrax approved these changes
I think this resolves all the concerns that were brought up in this week's VCWG meeting.

2023-10-06 20:47 UTC, msporny commented
> This spec is still referencing ?MULTIBASE rather than normative definitions of the features used.

Sorry, there was code stuck on my local copy that removed all those references, requesting another re-review from you.

2023-10-06 21:09 UTC, seabass-labrax approved these changes

2023-10-11 03:59 UTC, msporny commented
@selfissued re-ping to re-review... ideally, you approve before we merge this. It's all green on reviews so far.

2023-10-11 17:09 UTC, selfissued approved these changes
Thanks for doing this.

2023-10-11 19:19 UTC, dmitrizagidulin approved these changes

2023-10-12 06:13 UTC, iherman commented
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-10-11-vcwg#section1-3) on 2023-10-11

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.3. Make all Multicodec / Multibase references non-normative. (pr vc-di-ecdsa#42)

_See github pull request [vc-di-ecdsa#42](https://github.com/w3c/vc-di-ecdsa/pull/42)._




**Manu Sporny:** I see he's approved the last remaining well as well.  
… That is great, that unblocks us across the board for all DI and cryptosuite specs.  
… That's that item, we can shift back to VCDM.  

**Brent Zundel:** There are a lot of VCDM PRs.  

</details>

2023-10-12 18:54 UTC, msporny commented
Normative, multiple reviews, changes requested and made, no objections, merging.

2023-10-12 18:54 UTC, merged