Editorial Review:  Update references, check wording, formatting, and such
w3c/vc-di-ecdsa pull request #71
Opened 2024-08-21 17:42 UTC by Wind4Greg

Editorial review and  edits  for  readability and clarity.  Mostly fixes  to broken  references.

2024-08-22 19:00 UTC, TallTed requested changes

2024-08-22 19:00 UTC, TallTed commented on index.html
> +[[controller-document]] specification,
```suggestion
[[[controller-document]]] specification,
```

2024-08-22 19:00 UTC, TallTed commented on index.html
> +[[controller-document]] specification,
```suggestion
[[[controller-document]]] specification,
```

2024-08-22 19:00 UTC, TallTed commented on index.html
> +Multibase section</a> of [[controller-document]]. That is, return a string
```suggestion
Multibase section</a> of [[[controller-document]]]. That is, return a string
```

2024-08-22 19:00 UTC, TallTed commented on index.html
> +Multibase section</a> of [[controller-document]]. That is, return a string
```suggestion
Multibase section</a> of [[[controller-document]]]. That is, return a string
```

2024-08-22 19:00 UTC, TallTed commented on index.html
> +The required inputs are a derived proof value (|proofValue|).
```suggestion
The required input is a derived proof value (|proofValue|).
```

2024-08-28 14:49 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2024-08-28 14:49 UTC, merged